### ISSUE TITLE
/var/volatile tmpfs size

### ISSUE THREAD

**Issue by rienafairefr** [iot-lab/iot-lab-yocto#26]
I wanted to do some testing of iot-lab-gateway on a node (fixing the firefly firmware update bug) and it was failing because the /var/volatile folder was getting full during the `sdist` phase of installing gateway_code on the node. By default the tmpfs partition is sized to half of the RAM, so on Rpi3 gateways it gets around 430 M, and on varisicite it gets around 125 M. It's solvable temporarily by remounting /var/volatile with a different size.
We can resize the partition on mounting, by modifying /etc/fstab but i'm not sure about the implications, I might be missing something. 

just modifying `poky/meta/recipes-core/base-files/base-files/fstab` in yocto with a size=XX parameter (maybe putting size=500M across the board) to /var/volatile would do the trick I guess ?

**Comment by aabadie** [comment]
I felt into the same problem after the last release of the gateway code: the CI Yocto images were still using the previous gateway_code and running the tests on them required to install the gateway_code with pip globally. I guess this is because of the control_node_serial or something.

So the solution was to simply deploy the latest image which contains the same gateway_code version => then no need to install it again globally using pip => no pip directory created in /tmp.

So, of course the space left in /tmp is still tight but it works.

I'm closing this but feel free to reopen if you disagree.
