### ISSUE TITLE
update-rc.d

### ISSUE THREAD

**Issue by rienafairefr** [iot-lab/iot-lab-yocto#6]
Copier-coller:

Apparemment update-rc.d était disponible sur les images pour les gateway, c'est utilisé dans le python setup.py release, mais avec l'image yocto, update-rc.d n'est pas trouvé/installé ?

> fsaintma:

bon la ca devient complique
ca ressemble a un bug yocto qui pour une raison obscure qui supprime le package update-rc.d
au moment du build de la gateway
pas trouve encore de workaround
je continue demain

**Comment by fsaintma** [comment]
A good reason :) We had read-only-rootfs in IMAGE_FEATURES. So I try to find a workaround

Previously, the following list of packages were removed if package-management was not in IMAGE_FEATURES, regardless of any dependencies:

     update-rc.d
     ...
                    
With the Yocto Project 2.1 release, these packages are only removed if "read-only-rootfs" is in IMAGE_FEATURES, since they might still be needed for a read-write image even in the absence of a package manager (e.g. if users need to be added, modified, or removed at runtime).
